
preparepandoc:
  image: registry.gitlab.com/tibhannover/oer/course-pandoc-preparation
  stage: build
  script:
    - course.md
  artifacts:
    untracked: true
    expire_in: 5min

pages:
  image: ntwrkguru/pandoc-gitlab-ci
  stage: deploy
  dependencies:
    - preparepandoc
  script:
    - ls -l
    # generate output files
    - pandoc title.txt course-prepared.md -f markdown -t epub3 -s -o course.epub --metadata pagetitle="Kursbeispiel" --webtex
    - pandoc title.txt course-prepared.md -f markdown -t latex -s -o course.pdf --metadata pagetitle="Kursbeispiel" --webtex
    - pandoc title.txt course-prepared.md -f markdown -t html -s -o index.html --metadata pagetitle="Kursbeispiel" --include-in-header=metadata.json --katex --css pandoc.css
    - pandoc title.txt course-prepared.md -f markdown -t asciidoc -s -o course.asc --metadata pagetitle="Kursbeispiel" --webtex
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
  - master
